2023-2C-F-Estacionamiento/2023-2C-F-Estacionamiento/Models/Persona.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;

namespace _2023_2C_F_Estacionamiento.Models
{
    public class Persona : IdentityUser<int>
    {
        public Persona()
        {

        }

        public Persona(string nombre, string apellido, int dni , string email)
        {
            this.Nombre = nombre;
            this.Apellido = apellido;
            this.Dni = dni;
            this.Email = email;

        }

        //public int Id { get; set; }

        // public Guid Id2 { get; set; }
        public String Nombre { get; set; }

        public String Apellido { get; set; }


        [Required]

        public int Dni { get; set; }

        [Required]

        //Adecuacion de identityUser
        public override string Email
        {
            get { return base.Email; }
            set { base.Email = value; }
        }

        public String NombreCompleto
        {
            get
            {
                return $"{Apellido}, {Nombre}";
            }
        }

        public Direccion? Direccion { get; set; }

        public List<Telefono>? Telefonos { get; set; }


    }
}

2023-2C-F-Estacionamiento/2023-2C-F-Estacionamiento/Controllers/PersonasController.cs
using _2023_2C_F_Estacionamiento.Data;
using _2023_2C_F_Estacionamiento.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.FlowAnalysis.DataFlow;

namespace _2023_2C_F_Estacionamiento.Controllers
{
    public class PersonasController : Controller
    {

        //Creo un DB context. Fuerzo a recibir un contexto de base de datos
        private readonly EstacionamientoContext _contexto;

        public PersonasController(EstacionamientoContext contexto)
        {
            this._contexto = contexto;
        }


        public IActionResult Index()
        {
            List<Persona> personasEnDb = _contexto.Personas.ToList();

            return View(personasEnDb);

            //Me manda a Crear 
            //return RedirectToAction("Crear");
        }

        public ActionResult Create()   //Ejemplo Con Get
        {
            

            return View();

        }

        public ActionResult CreatePost() //Ejemplo con Post
        {


            return View();

        }

        //Si no me pasan el dato que tiene el signo de parentesis me llega null , lo hago para que me envie cero si es un dato valido ya que el int lo inciializa en 0
        public ActionResult Crear(string nombre , string apellido,int id , int ?dni )
        {
            Persona persona = new Persona()
            { Nombre = nombre,
                Apellido = apellido,
                Id = id,
             // Dni = dni.Value  // pongo .value cuando el valor permite null. En este caso acepto null , 
            };

           // _contexto.Add(persona);
            //_contexto.SaveChanges();

            //Responde un Texto plano
            // return Content($"OK se creo a la Persona {persona.NombreCompleto} y el Id es {persona.Id} ");

            //Le mando la Persona como modelo
            return View(persona);
        }


        //Creo una persona y la guardo en la Base de Datos  . Si no le madno mail me da error en al base de datos al guardar pues es un dato Required
        public ActionResult Crear2(string nombre="Luis Alberto", string apellido = "Spinetta" , string email = "Luis@a.com")
        {
            Persona persona = new Persona()
            {
                Nombre = nombre,
                Apellido = apellido,
                Email = email
                // Dni = dni.Value  // pongo .value cuando el valor permite null. En este caso acepto null , 
            };

            _contexto.Add(persona);
            _contexto.SaveChanges();
            

            //Responde un Texto plano
            // return Content($"OK se creo a la Persona {persona.NombreCompleto} y el Id es {persona.Id} ");

            //Le mando la Persona como modelo
            return RedirectToAction("Index");
        }

        public IActionResult Repository()
        {
            //  creo las Personas que traigo de la DB y la hago tolist

            //  List<Persona> Personas = _contexto.Personas.ToList();

            var personas = new PersonasRepository();
            //lista de personas

            //Lo guardo uno a uno en la base de datos
            foreach (Persona persona  in personas.Personas)
            {
                _contexto.Add(persona);
                _contexto.SaveChanges();
            }
           
           

            return View(personas.Personas);

           

            // return View(_contexto.Personas);
        }



    }
}

2023-2C-F-Estacionamiento/2023-2C-F-Estacionamiento/Views/Personas/Crear.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Persona

<!--USO DE TAG HELPERS si lo veo en codigo fuente F12 veo que creo esto <a href="/Personas/Crear">Crear</a>-->
<a asp-action="Crear" asp-controller="Personas">Crear</a>

<div>
    <h2>Los Datos de la Personas son :</h2>

    <ul>
        <li>
            <p>el nombre completo es @Model.NombreCompleto</p>
        </li>

    </ul>

</div>

2023-2C-F-Estacionamiento/2023-2C-F-Estacionamiento/Views/Personas/CrearPersona.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

2023-2C-F-Estacionamiento/2023-2C-F-Estacionamiento/Views/Personas/Create.cshtml
@model _2023_2C_F_Estacionamiento.Models.Persona

@{
    ViewData["Title"] = "Create";
}

<h1>View</h1>

<h4>Persona</h4>


<form method="get" action="@Url.Action("Crear", "Personas")">
    <div class="form-group">
        <label for="Nombre">Ingrese su nombre</label>
        <input type="text" id="Nombre" name="Nombre" class="form-control" />
        <label for="Apellido">Ingrese su Apellido</label>
        <input type="text" id="Apellido" name="Apellido" class="form-control" />

    </div>
    <button type="submit" class="btn btn-primary">Enviar</button>
</form>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

2023-2C-F-Estacionamiento/2023-2C-F-Estacionamiento/Views/Personas/CreatePost.cshtml
@model _2023_2C_F_Estacionamiento.Models.Persona

@{
    ViewData["Title"] = "Create Post";
}

<h1>View</h1>

<h4>Persona</h4>

<form action="@Url.Action("Crear", "Personas")" method="post">
    <div class="form-group">
        <label for="nombre">Nombre</label>
        <input type="text" class="form-control" id="nombre" name="nombre" required>
    </div>
    <div class="form-group">
        <label for="apellido">Apellido</label>
        <input type="text" class="form-control" id="apellido" name="apellido" required>
    </div>
    
    <button type="submit" class="btn btn-primary">Enviar</button>
</form>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

2023-2C-F-Estacionamiento/2023-2C-F-Estacionamiento/Views/Personas/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

2023-2C-F-Estacionamiento/2023-2C-F-Estacionamiento/Views/Personas/Index1.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

2023-2C-F-Estacionamiento/2023-2C-F-Estacionamiento/Views/Personas/Repository.cshtml
@model List<Persona>

    <p>Las Personas en la lista son</p>

    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th>
                    Nombre
                </th>

                <th>
                    Apellido
                </th>
            </tr>
        </thead>



        <tbody>
            @foreach (Persona persona in Model)
            {
                <tr>
                    <td> @persona.Nombre</td>
                    <td> @persona.Apellido</td>
                </tr>

            }

        </tbody>
    </table>

2023-2C-F-Estacionamiento/2023-2C-F-Estacionamiento/Views/Personas/index.cshtml
@model List<Persona>


<h2>Estas son las Personas creadas Con nuestra webApp</h2>

@foreach (Persona persona in Model)
{
    <p>@persona.NombreCompleto</p>
}